version: '3'

services:

    dind:
        build: .
        container_name: 'dind'
        restart: 'unless-stopped'
        ports:
            - '2222:22/tcp'
        volumes:
            - 'dind:/home/dind'
        environment:
            - 'TZ=America/Toronto'
            - 'GITHUB_USER=klutchell'
        privileged: true

volumes:

    dind:
